### PR TITLE
Dear Moby Extension

### PR DESCRIPTION
**Pull request by Shy**
Added first pass at Dear Moby Extension

### CODE REVIEW

**Comment by benja-M-1** [comment]
@Shy don't you want this extension to have its repo and eventually publish it on the marketplace?

**Comment by Shy** [comment]
I'd like it in the marketplace, but I feel like it's most useful as an example for folks looking at the SDK. I can't see the extension getting tons of traffic beyond as an example. I can move it to a unique repo if that adds to much extra complexity.

**Comment by benja-M-1** [comment]
I don't have a strong opinion. The only thing I can think of is that the number of people being notified if there are issue related to the extension that shouldn't be :)

**Comment by Shy** [comment]
I don't think we'll get a ton of traffic around that but if it's a problem we can always pull it out.

**Pull request closed without merging**
